name: mpflutter_wechat_socket
description: "The socket adapter in wechat miniprogram"
version: 0.0.1

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  mpflutter_core: ">=2.0.0"
  mpflutter_wechat_api: ">=2.0.0"